### ISSUE TITLE
Bi-Weekly Scrum - May 29

### ISSUE THREAD

**Issue by IsabellaLCYang** [IsabellaLCYang/Simp.Com#1]
Submit scrum below as comments.

**Comment by IsabellaLCYang** [comment]
CSID: m9e3b
I worked on finalizing our project ideas and details such as the user interactions that our web application will support. The major issue is organizing all the proposed user stories cohesively into one dashboard interface without being too scattered and deviated from our central idea. We will be working on dividing our project into phases and assigning tasks for each person to complete in the 2-week period. We will also create detailed prototypes with Figma before proceeding to actual implementation.  I will be making the UI for the cart and order tracking page for logged-in customers and guests.

**Comment by Gavinygh** [comment]
CSID: n5l3b

I contributed to coming up with project ideas and deciding on the final topic. As well, I described some details of the sketch UI such as the layout of the navbar. The major issue we encountered was deciding which project idea should we adhere to and how to sketch the UI pages such that they have places for all functionalities we proposed. We met on zoom today, talking and designing the template UI pages for project progress 2. In the end, we split our work by assigning tasks of designing template UI pages. I will be working on the design of the navbar as well as the homepage for buyers.

**Comment by royroyzhong** [comment]
CSID: a7u2b 
I brainstormed some project ideas, provided some feature ideas, confirmed the project requirement, and drew UI with Figma during our previous iteration's meeting. A critical issue at this point is that we have no idea how long it will take to complete each minimum requirement because we have only recently learned the react and redux. In the following step, I will search the MaterialUi template and discuss the final template with our team. Also, I will use react to build the frontend for the user login page and user profile page for customers and business owners.

**Comment by t-quinn-t** [comment]
CSID: y3z2b

I participated in the project idea discussion and collaborated with other teammates to finalize our basic prototype. Getting the prototype done is itself a major challenge as we found ourselves facing a lot of details that we have not thought of in the rough sketch. So for the next week, we will continue working on prototypes and start creating some views. I will be working on the dashboard (not including the menu bar component), the product page and also the product edit page.
