### ISSUE TITLE
Biweekly Scrum Jun 12th

### ISSUE THREAD

**Issue by IsabellaLCYang** [IsabellaLCYang/Simp.Com#36]

**Comment by IsabellaLCYang** [comment]
Name: Isabella(Lichuan) Yang
I worked on making the UI for cart and order tracking including designing components and using external sources like MUI for better presentation. With my group members, we also created designs for each page in Figma. The major issue is organizing the grid and boxes to yield a visual with an appropriate layout and sizing for each box.  I will start designing popup for submitting unprocessed orders and the orders page for customer for the next phase.

**Comment by Gavinygh** [comment]
Name: Gavin (Guanghua) Yang

We initially drew the prototype of each page on Figma and then assigned the task of designing the web pages to each team member. I worked on designing the UI for the navigator and customer homepage, implemented with external library MUI. As well, I provided the framework for combining the components with navigator. The major issue was integrating different components like combining navigator, headers, and page-right content, and adjusted the parameters of components to make their layout coordinated. As for the next progress, I will continue working on the optimization of UI, as well as adding at least 2 actions (adding, deleting products) on the buyer side.

**Comment by royroyzhong** [comment]
Ruming(Roy) Zhong

I used MUI to create the login and profile pages, as well as complete some of the functionality for these pages (the password rule will be responsive when user enter their password in the change password feature). I also use the navigator hook to link all of the pages together for demo purposes, as well as the media query hook to adjust the responsive webpage. Since our team decided on a common navigation bar and top header, I'm having trouble putting things together. The use of space and container varies depending on personal preference, and using the library straight away does not assist in adjusting the responsive webpage. The next step is to create the backend folder, add items to the backend, use redux to store password changes and user information when the user signs up and adjust the UI to achieve a perfect responsive webpage.

**Comment by t-quinn-t** [comment]
Qintu (Quinn) Tao, y3z2b 

I worked on seller side Dashboard and Product editable pages. Major issue is configuring CSS, even though MUI already rendered a part of styling itself. The next steps would be: upgrading the existing redux store so that it generalize the `user` and `products` states. Also, the Router we used for navigation has some minor problems where some of page are not visible so far. This needs to be fixed in the next iteration as well.
