### ISSUE TITLE
Biweekly Scrum Reports Jun 26th

### ISSUE THREAD

**Issue by IsabellaLCYang** [IsabellaLCYang/Simp.Com#57]
Name: Isabella(Lichuan) Yang
I worked on making the UI for buyer order tracking including designing components and implementing the cart slice and order slice as well as their associated actions triggered by buttons in UI. As a group, we discussed the fields for major data types like products and orders. I will be working on building backend with express for cart and order tracking for both seller and user. Then our group will decide and implement the data structure for the major data types as well as image processing in MongoDB. The major issue I encountered is we're missing some integration across webpages, so the possible actions I can dispatch is limited as most of them will require a collaboration of several pages to achieve one goal,

**Comment by royroyzhong** [comment]
Name: Ruming Zhong
I worked on making the Google Login API, user authentication, improve some UI design. I also created middleware to verify user jwt, check the dup user when they register, and generator jwt when they log in. It takes me time to figure out the user auth and router in the backend since they are many ways to do it, but finding a way to fix it for our project takes some time. For the next step, I will fix the route, create more API, connect our DB, and put some data into it. And also, I will plan to finish the encrypted password

**Comment by Gavinygh** [comment]
Name: Gavin (Guanghua) Yang

I worked on optimizing the UI for the navigator and header, specifically, I combined the navigator and header as one component, and the navigator can be shrunk. The major challenge I encountered was how to use and edit the style parameters of MUI Appbar and Drawer to achieve making the navigator shrinkable. As for the next progress, I will be working on building a backend with express for product data on the buyer side. Then design and implement the data structure for several data types in MongoDB.

**Comment by t-quinn-t** [comment]
Name: Quinn Tao
I worked on refactoring reducers for product page and product editing page. Also improved a little bit of UI where the user can now add titles to products. For the next sprint, I will be working on move data to our express back-end. Including storing list of products sold by specific seller to express and db.
